version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
    # requires manual upgrade as we use internal interfaces
    - dependency-name: "lighthouse"
    # doesn't support glob anymore in v4
    - dependency-name: "rimraf"
- package-ecosystem: npm
  directory: "/"
  target-branch: v7
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
    # packages we don't update for v7 anymore
    - dependency-name: "@types/jasmine"
    - dependency-name: "ky"
    - dependency-name: "jasmine"
    - dependency-name: "puppeteer-core"
    - dependency-name: "serialize-error"
    # moved to ESM only
    - dependency-name: "del"
    - dependency-name: "got"
    - dependency-name: "long"
    - dependency-name: "tempy"
    - dependency-name: "inquirer"
    - dependency-name: "url-join"
    - dependency-name: "camelcase"
    - dependency-name: "pretty-ms"
    - dependency-name: "dateformat"
    - dependency-name: "strip-ansi"
    - dependency-name: "supports-color"
    # requires manual upgrade as we use internal interfaces
    - dependency-name: "lighthouse"
    # Chalk v5 is ESM only
    - dependency-name: "chalk"
      update-types: ["version-update:semver-major"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
