version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
    # requires manual upgrade as we use internal interfaces
    - dependency-name: "lighthouse"
- package-ecosystem: npm
  directory: "/"
  target-branch: v8
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
    # requires manual upgrade as we use internal interfaces
    - dependency-name: "lighthouse"
    # doesn't support glob anymore in v4 (Windows)
    - dependency-name: "rimraf"
    # these packages don't support Node.js v16 anymore
    - dependency-name: "got"
    - dependency-name: "ky"
    - dependency-name: "@octokit/rest"
    - dependency-name: "@cucumber/cucumber"
    - dependency-name: "jsdom"
    - dependency-name: "pretty-ms"
    - dependency-name: "@puppeteer/browsers"
    - dependency-name: "inquirer"
    - dependency-name: "read-pkg-up"
    - dependency-name: "formdata-node"
    # fails to update and requires investigations
    - dependency-name: "vite"
    - dependency-name: "puppeteer-core"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
