notifications:
  email: false

language: node_js

node_js:
  - '0.10'

sudo: false

branches:
  except:
    - /^v[0-9]/
  only:
    - master

before_script:
  - "npm install -g bower"
  - "cd test/site/www && bower install && cd ../../../"
  - "phantomjs --webdriver=4444 2>&1 >/dev/null &"
  - "2>/dev/null 1>/dev/null python -m SimpleHTTPServer 8080 &"

script: "sleep 5 && npm run coverage"

after_script:
  - "[ -d ./coverage ] && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"

addons:
  sauce_connect: true

env:
  global:
    - secure: f6+NU5WBW9GPLRV2WhtCozPOjFOAdh52hXfr0dZopxl0eqJ426fl5UCt54duUQV/abBpNEKzBm2015EsBP14wepNJ9+Q6nRwrj/h2PvI3UM8vEPqgH08hqiS7kFszA0Wy+Ki3umncQbA5WAgq6grmZs9naELWmOX5Yum40Wl9/0=
    - secure: dMTVz/kDqs+qBMqB6CZEHrvSYIkqxCTa0fnVPNH1vyiJ02a66yQrZhdxH6PrZjk8iYW8CAh8mLjrYlaOAPG6UL3gjecYVCegyMKIU3GI6CgBYOQOaU4xo2ypK7COqHkRYPJ+G5fyQfcZrB97iccpC1CUy88R0pGq/sb3teKTV7w=

  matrix:
    - _BROWSER: "chrome"
      _PLATFORM: "Windows_8"
      _VERSION: "34"
      _ENV: "desktop"
    - _BROWSER: "firefox"
      _PLATFORM: "Windows_8"
      _VERSION: "29"
      _ENV: "desktop"
    - _BROWSER: "internet_explorer"
      _PLATFORM: "Windows_8"
      _VERSION: "10"
      _ENV: "desktop"
    - _BROWSER: "Safari"
      _PLATFORM: "iOS"
      _APP: "safari"
      _DEVICENAME: "iPhone_Simulator"
      _VERSION: "7.1"
      _ENV: "mobile"
    - _BROWSER: "Safari"
      _PLATFORM: "iOS"
      _APP: "safari"
      _DEVICENAME: "iPad_Simulator"
      _VERSION: "7.1"
      _ENV: "mobile"
    # - _PLATFORM: "Linux"
    #   _BROWSER: "android"
    #   _DEVICENAME: "Google_Nexus_7_HD_Emulator"
    #   _VERSION: "4.3"
    #   _ENV: "mobile"
    # - _PLATFORM: "Linux"
    #   _BROWSER: "Android"
    #   _DEVICENAME: "Samsung_Galaxy_Nexus_Emulator"
    #   _VERSION: "4.3"
    #   _ENV: "mobile"
    - _BROWSER: "phantomjs"
      _ENV: "functional"
    - _ENV: "multibrowser"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d8bf1012f1edc18cd839
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
