notifications:
  email: false
language: node_js
node_js:
  - '0.10'
before_script:
  - curl -O http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar
  - java -jar selenium-server-standalone-2.39.0.jar &
  - python -m SimpleHTTPServer 8080 &
addons:
  sauce_connect: true
env:
  global:
    - SAUCE_USERNAME: "webdriverjs"
    - SAUCE_ACCESS_KEY: "6ccbed11-96f8-4199-901d-b9a93bdbc376"

  matrix:
    - _BROWSER: "chrome"
      _PLATFORM: "Windows_8"
      _VERSION: "31"
    - _BROWSER: "firefox"
      _PLATFORM: "Windows_8"
      _VERSION: "25"
    - _BROWSER: "firefox"
      _PLATFORM: "Linux"
      _VERSION: "25"
    - _BROWSER: "phantomjs"
      _PLATFORM: ""
      _VERSION: ""