name: Build WebdriverIO

on:
  workflow_call:
  # Make this a reusable workflow, no value needed
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: ğŸ§‘â€ğŸ”§ Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: ğŸ‘· Bootstrap Packages
        run: pnpm run setup
        shell: bash
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ—ï¸ Generate Typings
        run: pnpm run generate:typings
        shell: bash

      - name: â¬†ï¸ Upload Build Artifacts
        uses: ./.github/workflows/actions/upload-archive
        with:
          name: webdriverio
          output: webdriverio-build.zip
          paths: packages/*/build packages/*/cjs
