name: Smoke Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  check:
    name: Smoke Test (${{ matrix.os }}.${{ matrix.node }})
    permissions:
      contents: read
      actions: write
    strategy:
      fail-fast: false
      matrix:
        node: ['18.20.0', '20', '22']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ğŸ§‘â€ğŸ”§ Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: ğŸ¢ Setup Node ${{ matrix.node }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: ğŸ“¦ Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: webdriverio
          path: .
          filename: webdriverio-build.zip

      - name: ğŸ§ª Smoke Tests
        run: pnpm run test:smoke
        shell: bash

      - name: ğŸ” Check Git Context
        if: matrix.os != 'windows-latest'
        uses: ./.github/workflows/actions/check-git-context
