name: CJS Interoperability Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  check:
    name: CJS Interoperability Tests
    runs-on: 'ubuntu-latest'
    steps:
      - name: Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: webdriverio
          path: .
          filename: webdriverio-build.zip

      - name: CJS Interoperability Tests
        run: |
          pnpm run link
          pnpm run test:interop
        shell: bash

      - name: Check Git Context
        uses: ./.github/workflows/actions/check-git-context
