name: Unit Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  check:
    name: Unit Test (${{ matrix.os }}.${{ matrix.node }})
    permissions:
      contents: read
      actions: write
    strategy:
      fail-fast: false
      matrix:
        node: ['20', '22', '24']
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: ‚¨áÔ∏è Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: üßë‚Äçüîß Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: üê¢ Setup Node ${{ matrix.node }}
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: webdriverio
          path: .
          filename: webdriverio-build.zip

      - name: Unit Tests
        run: pnpm run test:unit:run
        shell: bash

      - name: Check Git Context
        # currently fails in Windows due to changes to snapshots
        # in packages/wdio-browser-runner/tests/vite/__snapshots__/utils.test.ts.snap
        if: matrix.os != 'windows-latest'
        uses: ./.github/workflows/actions/check-git-context
