name: Static Code Analysis

on:
  merge_group:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  check:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Dependency Check
        run: pnpm run test:depcheck
        shell: bash

      - name: Eslint
        run: pnpm run test:eslint
        shell: bash

      - name: EJS Lint
        run: pnpm run test:ejslint
        shell: bash

