name: Cloud Connection Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  cloud_check:
    name: Cloud Connection Tests
    runs-on: 'ubuntu-latest'
    if: github.ref == 'refs/heads/main'
    steps:
      - name: ‚¨áÔ∏è Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: üßë‚Äçüîß Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: webdriverio
          path: .
          filename: webdriverio-build.zip

      - name: E2E Connection Test
        run: pnpm run test:e2e:cloud
        if: github.ref == 'refs/heads/main'
        env:
          SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
          SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

      - name: E2E Connection Test w/ Params
        run: pnpm run test:e2e:cloud --user $SAUCE_USERNAME_PARAM --key $SAUCE_ACCESS_KEY_PARAM
        if: github.ref == 'refs/heads/main'
        env:
          SAUCE_USERNAME_PARAM: ${{secrets.SAUCE_USERNAME}}
          SAUCE_ACCESS_KEY_PARAM: ${{secrets.SAUCE_ACCESS_KEY}}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-cloud-connection-tests-logs
          path: e2e/wdio/*.log

      - name: Check Git Context
        uses: ./.github/workflows/actions/check-git-context
