name: CJS Interoperability Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  check:
    name: CJS Interoperability Tests
    permissions:
      contents: read
    runs-on: 'ubuntu-latest'
    steps:
      - name: ‚¨áÔ∏è Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: üßë‚Äçüîß Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: webdriverio
          path: .
          filename: webdriverio-build.zip

      - name: CJS Interoperability Tests
        run: pnpm run test:interop
        shell: bash

      - name: Check Git Context
        uses: ./.github/workflows/actions/check-git-context
