name: Testrunner Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  testrunner_check:
    name: Testrunner Tests (${{ matrix.os }})
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-15']
    runs-on: ${{ matrix.os }}
    steps:
      - name: ‚¨áÔ∏è Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: üßë‚Äçüîß Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: webdriverio
          path: .
          filename: webdriverio-build.zip

      - name: Testrunner Tests
        run: |
          pnpm run test:e2e:testrunner
          pnpm run test:e2e:classic
        shell: bash

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: failure()
        with:
          name: e2e-testrunner-tests-logs
          path: e2e/wdio/*.log

      - name: Check Git Context
        if: matrix.os != 'windows-latest'
        uses: ./.github/workflows/actions/check-git-context
