name: 'Get Core Dependencies'
description: 'sets the node version & initializes core dependencies'
runs:
  using: composite
  steps:
    - name: ğŸ“¦ Setup pnpm
      uses: pnpm/action-setup@7088e561eb65bb68695d245aa206f005ef30921d # v4.1.0

    - name: ğŸ¢ Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: ğŸ—ï¸ Install Dependencies
      run: pnpm install
      shell: bash

    - name: ğŸ”§ Git Config
      run: git config --global core.autocrlf false
      shell: bash
