name: 'Get Core Dependencies'
description: 'sets the node version & initializes core dependencies'
permissions:
  contents: read # to fetch code (actions/checkout)
runs:
  using: composite
  steps:
    - name: â¬‡ï¸ Checkout Code
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

    - name: ğŸ“¦ Setup pnpm
      uses: pnpm/action-setup@v4

    - name: ğŸ¢ Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'pnpm'
    - name: ğŸ—ï¸ Install Dependencies
      run: pnpm install
